site_name: Taskgrader
pages:
- "Home": index.md
- "Getting started":
    - "Installing": install.md
    - "Basic usage": basicusage.md
    - "Writing tasks": writing.md
    - "Task examples": examples.md
- "Reference":
    - "Conventions": conventions.md
    - "taskSettings.json": tasksettings.md
    - "defaultParams.json": defaultparams.md
    - "Input JSON": inputjson.md
    - "Output JSON": outputjson.md
- "Error messages": errors.md
- "Further information": moreinfo.md
repo_url: https://github.com/France-ioi/taskgrader/
site_description: Documentation for the taskgrader
site_author: France-IOI
